language: generic
matrix:
  include:
    - script:
        - make test
        - pod lib lint
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.2
      before_install:
        - pod repo update
    - script:
        - swift test
        - swiftlint
      env: JOB=SPM
      os: osx
      osx_image: xcode8.2
    - script: make docker_test
      env: JOB=Linux
      sudo: required
      services: docker
    - script: >
        docker run -v `pwd`:/SourceKitten norionomura/sourcekit:3120170131a bash -c "cd /SourceKitten &&
        swift package edit Commandant --revision nn-swift-3.1-on-linux &&
        swift package edit Result --revision nn-swift-3.1-on-linux &&
        swift package edit Yams --revision master &&
        swift test"
      env: JOB=Linux-Swift3.1
      sudo: required
      services: docker
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
